name: Variables Lab

on:
    push:
        branches:
            - main

env:
    APPLICATION: github-action-learning

jobs:

    information:
        runs-on: ubuntu-latest

        env:
            ENVIRONMENT: learning
        
        steps:
            - name: Show application
              run: |
                echo "Application: ${{ env.APPLICATION }}"

            - name: Show environment
              run: |
                echo "Environment: ${{ env.ENVIRONMENT }}"
            
            - name: Show repository
              run: |
                echo "Repository: ${{ github.repository }}"
                echo "Repository: $GITHUB_REPOSITORY"

            - name: Show branch
              run: |
                echo "Branch: ${{ github.ref_name }}"
                echo "Branch: $GITHUB_REF_NAME"

            - name: show commit
              run: |
                echo "Commit: ${{ github.sha }}"
                echo "Commit: $GITHUB_SHA"

            - name: show actor
              run: |
                echo "Actor: ${{ github.actor }}"
                echo "Actor: $GITHUB_ACTOR"